### ISSUE TITLE
please tag versions

### ISSUE THREAD

**Issue by boutil** [immutable-ruby/immutable-ruby#9]
Hi,
Could you please tag the commits corresponding to a released gem version? This would allow distributions to be able to track changes and easily access code for tests corresponding to a new version, and run them for integration purposes. Thanks in advance!

**Comment by alexdowad** [comment]
Hi @boutil. I actually have been tagging the commits for all released gem versions, but hadn't pushed the tags to GH. That has been done now.

I have just pushed the tags for 0.1.0 and 0.0.4. If you want a tag for any other version, comment below.

**Comment by boutil** [comment]
thanks a lot!
